/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef featured_CONSTANTS_H
#define featured_CONSTANTS_H

#include "featured_types.h"

namespace featured {

class featuredConstants {
 public:
  featuredConstants();

};

extern const featuredConstants g_featured_constants;

} // namespace

#endif
