/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "featured_constants.h"

namespace featured {

const featuredConstants g_featured_constants;

featuredConstants::featuredConstants() {
}

} // namespace

