// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FeaturedService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::featured;

class FeaturedServiceHandler : virtual public FeaturedServiceIf {
 public:
  FeaturedServiceHandler() {
    // Your initialization goes here
  }

  void get_features(std::vector<std::string> & _return) {
    // Your implementation goes here
    printf("get_features\n");
  }

  void select(std::vector<Item> & _return, const Select& select_query) {
    // Your implementation goes here
    printf("select\n");
  }

  void shutdown() {
    // Your implementation goes here
    printf("shutdown\n");
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<FeaturedServiceHandler> handler(new FeaturedServiceHandler());
  shared_ptr<TProcessor> processor(new FeaturedServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

